set nocompatible

let mapleader=","
let maplocalleader=","

set shell=bash

filetype off

" ------------------------------------------------
" PLUGINS

call plug#begin()

    Plug 'andreasvc/vim-256noir'

    " clever-f

    Plug 'rhysd/clever-f.vim'
        let g:clever_f_across_no_line = 1

    " t-comment

    Plug 'tomtom/tcomment_vim'

    " fugitive-vim

    Plug 'tpope/vim-fugitive'

    " easymotion
    
        Plug 'easymotion/vim-easymotion'	

        let g:EasyMotion_smartcase = 1

        " <Leader>f{char} to move to {char}
        map  <Leader>f <Plug>(easymotion-bd-f)
        nmap <Leader>f <Plug>(easymotion-overwin-f)

        map <Leader>L <Plug>(easymotion-bd-jk)
        nmap <Leader>L <Plug>(easymotion-overwin-line)

        map  <Leader>w <Plug>(easymotion-bd-w)
        nmap <Leader>w <Plug>(easymotion-overwin-w)

        noremap  / <Plug>(easymotion-sn)
        onoremap / <Plug>(easymotion-tn)
        noremap  n <Plug>(easymotion-next)
        noremap  N <Plug>(easymotion-prev)


    " fzf

    Plug 'junegunn/fzf', { 'do': { -> fzf#install() } }
    Plug 'junegunn/fzf.vim'

        let g:fzf_nvim_statusline = 0
        nnoremap <silent> <leader><space> :Files<cr>
        nnoremap <silent> <leader>a :Buffers<cr>
        nnoremap <silent> <leader>; :BLines<cr>
        nnoremap <silent> <leader>gl :Commits<cr>
        nnoremap <silent> <leader>ga :BCommits<cr>

        imap <c-x><c-k> <plug>(fzf-complete-word)
        imap <c-x><c-f> <plug>(fzf-complete-path)
        imap <c-x><c-l> <plug>(fzf-complete-line)

    " ranger
    
    Plug 'francoiscabrol/ranger.vim'

        let g:ranger_map_keys = 0
        nnoremap <silent> <leader>r :Ranger<cr>

call plug#end()

" ------------------------------------------------
" OPTIONS

filetype plugin indent on

set shiftwidth=4
set expandtab
set tabstop=4

set display+=lastline
set scrolloff=2
set showcmd
set sidescroll=1
set smoothscroll
set ttyfast
set background=dark

set nowrap

" Status line

set laststatus=2
set showcmd
set showmode

" Title

set titlestring=%t\ -\ Vim

" Line Numbers

set number
set relativenumber
set nuw=6

" Search

set hlsearch
set incsearch
set showmatch
set smartcase
set ignorecase

nnoremap <silent> <esc> :noh<return><esc>

" Disable Matching Paren

    let c_no_curly_error=1
" ------------------------------------------------
" BINDINGS 

" Quick reload config file

noremap <leader>ev :e $MYVIMRC<cr>
noremap <leader>sv :so $MYVIMRC<cr>

" Save as sudo

cmap w!! w !sudo tee > /dev/null %

" Normal mode in terminal window

" tnoremap <leader><ESC> <C-\\><C-n>

" Colorscheme

syntax enable
set t_Co=256

colorscheme 256_noir

highlight CursorLine cterm=NONE ctermfg=NONE ctermbg=233 guifg=NONE guibg=#121212
autocmd InsertEnter * highlight CursorLine cterm=NONE ctermfg=NONE ctermbg=234 guifg=NONE guibg=#1c1c1c
autocmd InsertLeave * highlight CursorLine cterm=NONE ctermfg=NONE ctermbg=233 guifg=NONE guibg=#121212
